apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gtwx0ujxy-python
  janus-idp.io/tekton: gtwx0ujxy-python
  backstage.io/kubernetes-id: gtwx0ujxy-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gtwx0ujxy-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
