apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gtwx0ujxy-python-gitops
  description: This is GitOps manifest for gtwx0ujxy-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=gtwx0ujxy-python
    backstage.io/kubernetes-id: gtwx0ujxy-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gtwx0ujxy-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gtwx0ujxy-python
